# -*- coding: utf-8 -*-
"""5class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7U_aKFL4JjRYwrlhqKdIfYi8G_sESKp
"""

dict1 = {
    'namme' : "dhanush",
    'age' : 22,
    'location' : 'Nandya'
}

dict1

dict1.items()

dict1.get("age")

dict1.clear()

dict2 = {
    'namme' : "AK",
    'age' : 45,
    'location' : 'US'
}

dict1

dict2.pop("location")

dict2

dict2.update({'location' : 'USA'})

dict2

dict2.update({'location' : 'india'})

dict2

dict2.values()

dict2.keys()

nested_dict_2 = {
  "department1": {
    "employees": {
      "employee1_id": "raghav",
      "employee2_id": "riya"
    },
    "location": "Building A"
  },
  "department2": {
    "employees": {
      "employee3_id": "rajesh"
    },
    "location": "Building B"
  }
}

nested_dict_2

nested_dict_2['department1']['employees']['employee1_id']

nested_dict_2['department1']

nested_dict_2['department1']["employees"].update({"employee2_id" : "neha"})

nested_dict_2

