# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEMOAlsJRzvUZDMsEt3oT418OCZ6g8rF
"""

text = "Seras Victoria"
text

len(text)

text[0:5]

text.upper()

text.capitalize()

text.find('c')

text.count('s')

text.lstrip(text)

text.rstrip(text)

text.split()

"list datatypes"

list1 = [1,1.23,1+2j,"ssas"]
list1

type(list1)

type(list1[0]),type(list1[1]),type(list1[2]),type(list1[3])

list1[-1].upper()[0:3]

and also we can perform functions to the elements in the list directly

list1[0]+list1[1]

list1[1]+list1[2]

list1[2]

list1(3)

list1.append(225)

list1

list1.extend(56)

list1.extend('ss')

list1

list2 = list1

list2.append(11111)

list2

list1

list3=list1.copy()

list3.append(45)

list3,list1

the difference btw shallow copy and deep copy is shallow copy is made by assigning to main copy and if we make any changes in shallow copy it reflects in main copy to avoid this we use deep copy

list1.pop(2)

list1

list1.sort()

list3.pop(-3)

list3.remove('s')

list3

list3.pop(-5)

list3.sort()

list3.reverse()

list3

list3.clear()

list3



nested list

customers = [
    ["Ravi", ["Shampoo", "Toothpaste"]],
    ["Anjali", ["Rice", "Wheat", "Oil"]],
    ["Kiran", ["Biscuits", "Milk"]]
]

customers[0][0]

#to get oil
customers[1][1][2]



