# -*- coding: utf-8 -*-
"""Class 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lp8-B7y72OdUnwZiLrF-Ex8udq7OCbR4
"""

for i in range(0,10):
  if i==3:
    continue
  print(i)

for i in range(0,5):
  for j  in range(1,5):
    print(i,j)
    if j==5:
      break

for i in range(1,6):
  for j in range(1,6):
    print((i+j)//2,end=" ")
  print()

for i in range(0,5):
  for j in range(0,i+1):
    print((i+j)%2==0, end=" ")
  print( )

for i in range(0,5):
  for j in range(0,i+1):
    print((i+j)%2, end=" ")
  print( )

for i in range(5,0,-1):
  for j in range(i+1,0,-1):
    print((i+j)%2, end=" ")
  print( )

for i in range(0,6):
  for j in range(0,i+1):
    print((j), end=" ")
  print( )

for i in range(0,5):
  print((" *"*i).center(10," "))

for i in range(1,6):
  print((" *"*i).center(10," "))

for i in range(1,6):
  print((" *"*i).center(15," "))

