# -*- coding: utf-8 -*-
"""numpy class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytjwXz9F-hkibZrAa3rvL33RA7TCSume
"""

import numpy as np

data = np.random.randint(0,10,(4,4))
data

data.sum()

data.sum(axis=0) # axis 0 means y axis

data.sum(axis=1) # axis 1 means x axis

data.max()

data.min()

data.argmax() # index of max value

data.argmin() # index of min value

data.max(axis=0) # returns max element

data.argmax(axis=0)# returns index of max value in that axis

data.max(axis=1)

data.argmax(axis=1)

data

data.min(axis=0)

data.min(axis=0).sum()

data.argmin(axis=0)

data.argmin(axis=0).sum()

data=np.random.randint(0,10,(10,5))

data

data.sum(axis=0)

data.sum(axis=1)

data.max(axis=0)

data.max(axis=1)

data.sum()

data.max(axis=0).sum()

data.max(axis=1).sum()

#to get only selected column and row
data[0:7,:]

data[0:7,:].sum()

#another way
data.sum(axis=0)[:7]

data.sum(axis=0)[0:7].sum()

data=np.random.randint(0,10,10)
data

data.mean()

np.median(data)

np.mean(data)

np.quantile(data,0.25)

np.quantile(data,0.50)

np.quantile(data,0.75)

np.std(data)

np.var(data)

