# -*- coding: utf-8 -*-
"""Class 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLlaczsDwiRtulnlJt1JT81oN8h55Fre
"""

#for loop fundamental
for i in range(10):
    print(i)

for i in range(10):
    print(i,end=" ")
#vertical format

#for loop fundamental reverse
for i in range(10,0,-1):
    print(i)

#for nested list
my_nested_list = [
    ["apple", "red", "medium"],
    ["banana", "yellow", "small"],
    ["orange", "orange", "medium"]
]
for i in my_nested_list:
    print(i)

#for nested list
my_nested_list = [
    ["apple", "red", "medium"],
    ["banana", "yellow", "small"],
    ["orange", "orange", "medium"]
]
for i in my_nested_list:
    print(i,end = ' ')

a=[1,2,3,4,[5,6,7,8,9,0]]
for aa in a:
  print(aa)

#structures or pyramids
#code of colab
for i in range(1,6):
    for j in range(i):
        print("*",end=" ")
    print()

for i in range(1,6):
  print(i*'*')

for i in range(0,6):
  print(i*' *')

for i in range(5,0,-1):
  print(i*' *')

for i in range(6,1,-1):
  print('* '*i)

for i in range(0,6):
  print(i*' * ')
for i in range(6,0,-1):
  print(' * '*i)

for i in range(1,6):
  print(" "*(6-i)+ i*"*")

x=[1,2,3,4,5]
for i in range(1,6):
  print(x[0:i])

x="data science machine !%@%!@%!$5 learning"

for i in x:
  if not(i.isalpha()):
    print(i,end=",")























